branches:
  only:
  - travis-s390x

language: go

go:
- 1.12.8

os: linux
dist: focal

arch:
  - amd64
  - s390x

services:
  - docker

# env:  
#   global:
#   - SHORT_SHA=$(git rev-parse --short HEAD)

install: 
  - go get ${gobuild_args} ./...
  - export SHORT_SHA=$(git rev-parse --short HEAD)

script: |
      if [ "$TRAVIS_PULL_REQUEST" != "true" ]; then
        # Build machine-exec binary
        CGO_ENABLED=0 GOOS=linux go build -mod=vendor -a -ldflags '-w -s' -a -installsuffix cgo -o che-machine-exec .
        export CHE_WORKSPACE_ID=test_id
        # execute tests
        go test ./... -test.v

        # Build PR check image
        docker build -f build/dockerfiles/Dockerfile -t quay.io/prabhav/che-machine-exec:pr-check-${TRAVIS_CPU_ARCH} .
      fi

      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - echo "$QUAY_PASSWORD" |docker login quay.io -u "$QUAY_USERNAME " --password-stdin
        - docker build -f build/dockerfiles/Dockerfile -t quay.io/prabhav/che-machine-exec:nightly-${TRAVIS_CPU_ARCH} .
        - echo ${SHORT_SHA}
        - docker tag quay.io/prabhav/che-machine-exec:nightly-${TRAVIS_CPU_ARCH} quay.io/prabhav/che-machine-exec:${SHORT_SHA}-${TRAVIS_CPU_ARCH}
        - docker push quay.io/prabhav/che-machine-exec:nightly-${TRAVIS_CPU_ARCH}
        - docker push quay.io/prabhav/che-machine-exec:${SHORT_SHA}-${TRAVIS_CPU_ARCH}
      fi
