branches:
  only:
  - travis-s390x

language: go

go:
- 1.12.8

os: linux
dist: focal

services:
  - docker

# env:  
#   global:
#   - SHORT_SHA=$(git rev-parse --short HEAD)

install: 
  - export GO111MODULE="on" 
  - go get ${gobuild_args} ./...
  - export SHORT_SHA=$(git rev-parse --short HEAD)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$QUAY_PASSWORD" |docker login quay.io -u "$QUAY_USERNAME " --password-stdin

jobs:
  include:
   - stage: run unit test on amd64
     if: type = pull_request
     arch: amd64
     script: bash .travis/unit_tests.sh

   - name: run unit test on arm64
     if: type = pull_request
     arch: arm64
     script: bash .travis/unit_tests.sh

   - name: run unit test on ppc64le
     if: type = pull_request
     arch: ppc64le
     script: bash .travis/unit_tests.sh

   - name: run unit test on s390x
     if: type = pull_request
     arch: s390x
     script: bash .travis/unit_tests.sh

   - stage: build images
     on:
      branch: master
     name: build image with nightly/short_sha tag on amd64
     arch: amd64
     script:
       - bash .travis/build_nightly.sh

   - name: build image with nightly/short_sha tag on arm64
     on:
      branch: master
     arch: arm64
     script:
       - bash .travis/build_nightly.sh

   - name: build image with nightly/short_sha tag on ppc64le
     on:
      branch: master
     arch: ppc64le
     script:
       - bash .travis/build_nightly.sh

   - name: build image with nightly/short_sha tag on s390x
     on:
      branch: travis-s390x
     arch: s390x
     script:
       - bash .travis/build_nightly.sh
   
   - stage: Publish multiarch image
     script: bash .travis/publish_multiarch.sh