branches:
  only:
  - travis-s390x

language: go

go:
- 1.12.8

os: linux
dist: focal

services:
  - docker

# env:  
#   global:
#   - SHORT_SHA=$(git rev-parse --short HEAD)

install: 
  - export GO111MODULE="on" 
  - go get ${gobuild_args} ./...
  - export SHORT_SHA=$(git rev-parse --short HEAD)

jobs:
  include:
   - stage: run unit test on amd64
     if: type = pull_request
     arch: amd64
     script: bash .travis/unit_tests.sh

   - name: run unit test on arm64
     if: type = pull_request
     arch: arm64
     script: bash .travis/unit_tests.sh

   - name: run unit test on ppc64le
     if: type = pull_request
     arch: ppc64le
     script: bash .travis/unit_tests.sh

   - name: run unit test on s390x
     if: type = pull_request
     arch: s390x
     script: bash .travis/unit_tests.sh

   - stage: build images
     name: build image with nightly/short_sha tag on amd64
     arch: amd64
     script:
       - bash .travis/build_nightly.sh
     after_success: export AMD64_VERSION=nightly-"${TRAVIS_CPU_ARCH}"

   - name: build image with nightly/short_sha tag on arm64
     arch: arm64
     script:
       - bash .travis/build_nightly.sh
     after_success: export ARM64_VERSION=nightly-"${TRAVIS_CPU_ARCH}"

   - name: build image with nightly/short_sha tag on ppc64le
     arch: ppc64le
     script:
       - bash .travis/build_nightly.sh
     after_success: export PPC64LE_VERSION=nightly-"${TRAVIS_CPU_ARCH}"

   - name: build image with nightly/short_sha tag on s390x
     arch: s390x
     script:
       - bash .travis/build_nightly.sh
     after_success: export S390X_VERSION=nightly-"${TRAVIS_CPU_ARCH}"  

   - name: publish multiarch nightly image
     arch: amd64
     install: apt install skopeo jq
     script: bash .travis/publish_multiarch.sh
