language: go

go:
- 1.12.8

os: linux
dist: focal

services:
  - docker

env:  
   global:
   - TAG=nightly

install:
  - export GO111MODULE="on" 
  - go get ${gobuild_args} ./...
  - export SHORT_SHA=$(git rev-parse --short HEAD)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$QUAY_PASSWORD" |docker login quay.io -u "$QUAY_USERNAME " --password-stdin

jobs:
  include:
   - stage: run unit test on amd64
     if: type = pull_request
     arch: amd64
     script: bash .travis/unit_tests.sh

   - name: run unit test on arm64
     if: type = pull_request
     arch: arm64
     script: bash .travis/unit_tests.sh

   - name: run unit test on ppc64le
     if: type = pull_request
     arch: ppc64le
     script: bash .travis/unit_tests.sh

   - name: run unit test on s390x
     if: type = pull_request
     arch: s390x
     script: bash .travis/unit_tests.sh

   - stage: build images
     if: branch = travis-s390x AND env(TAG) = "nightly"
     name: build image with nightly/short_sha tag on amd64
     arch: amd64
     script:
       - bash .travis/build_nightly.sh $TAG

   - name: build image with nightly/short_sha tag on arm64
     if: branch = travis-s390x AND env(TAG) = "nightly"
     arch: arm64
     script:
       - bash .travis/build_nightly.sh $TAG

   - name: build image with nightly/short_sha tag on ppc64le
     if: branch = travis-s390x AND env(TAG) = "nightly"
     arch: ppc64le
     script:
       - bash .travis/build_nightly.sh $TAG

   - name: build image with nightly/short_sha tag on s390x
     if: branch = travis-s390x AND env(TAG) = "nightly"
     arch: s390x
     script:
       - bash .travis/build_nightly.sh $TAG
   
   - stage: Publish multiarch image
     script: bash .travis/publish_multiarch.sh $TAG

   - stage: Build images
     if: branch = travis-s390x AND env(TAG) != "nightly"
     name: build image with nightly/short_sha tag on amd64
     arch: amd64
     script:
       - bash .travis/build_nightly.sh $TAG

   - name: build image with nightly/short_sha tag on arm64
     if: branch = travis-s390x AND env(TAG) != "nightly"
     arch: arm64
     script:
       - bash .travis/build_nightly.sh $TAG

   - name: build image with nightly/short_sha tag on ppc64le
     if: branch = travis-s390x AND env(TAG) != "nightly"
     arch: ppc64le
     script:
       - bash .travis/build_nightly.sh $TAG

   - name: build image with nightly/short_sha tag on s390x
     if: branch = travis-s390x AND env(TAG) != "nightly"
     arch: s390x
     script:
       - bash .travis/build_nightly.sh $TAG

   - stage: Publish multiarch image
     install: true
     if: branch = travis-s390x AND env(TAG) != "nightly"
     script: bash .travis/publish_multiarch.sh $TAG
     after_success: bash make-release.sh --version $TAG --tag-release